<a href="https://colab.research.google.com/github/Fukutaro1010/python-basic-kadai/blob/main/kadai3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.array([[0, 1], [2, 3], [4, 5]])
b = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

c = np.dot(a, b)
print(c)
np.dot(a, b).max()


[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


47